server:
  port: 8443
  ssl:
    key-store: file:mykeys.jks
    key-store-password: 123456
    key-password: 123456

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
