server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
  data:
    rest:
      base-path: /data-api

  datasource:
    username: sa
    password:
    generate-unique-name: false
    name: tacocloud

logging:
  file:
    name: logs/TacoCloud.log

#My properties
taco:
  orders:
    page-size: 10

